name: Client Linter

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - main

jobs:
    linter:
        name: Linter
        runs-on: ubuntu-latest
        defaults: 
            run:
                working-directory: ./lifescape-app
        
        steps:
            - uses: actions/checkout@v4 

            - uses: dorny/paths-filter@v3
              id: filter
              with:
                filters: |
                  lifescape-app:
                  - 'lifescape-app/**'    
        
            - name: Set up Node.js
              if: steps.filter.outputs.lifescape-app == 'true'
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            
            - name: Install dependencies
              run: npm install
          
            - name: Run ESLint
              run: npm run lint --if-present --max-warnings=0