name: Server-Linter

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - main

jobs:
    linter:
        name: Linter
        runs-on: ubuntu-latest
        defaults: 
            run:
                working-directory: ./lifescape-server
        
        steps:
            - uses: actions/checkout@v4 
            
            - name: Install dependencies
              run: npm install
          
            - name: Run ESLint
              run: npm run lint --if-present